from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
import io
import datetime

class LegalDocBuilder:
    """
    Generates .docx files for legal correspondence.
    """
    
    @staticmethod
    def generate_letter(user_name: str, letter_data: dict) -> io.BytesIO:
        """
        Creates a formal letter based on AI-generated content.
        Returns a BytesIO object for Streamlit download.
        """
        doc = Document()
        
        # Styles
        style = doc.styles['Normal']
        font = style.font
        font.name = 'Times New Roman'
        font.size = Pt(12)

        # Header (Date)
        today = datetime.date.today().strftime("%B %d, %Y")
        p = doc.add_paragraph(today)
        p.alignment = WD_ALIGN_PARAGRAPH.RIGHT
        
        # Recipient Placeholder
        doc.add_paragraph(f"To: {letter_data.get('recipient_type', 'Recipient')}")
        doc.add_paragraph("[Recipient Address - Please Fill]")
        
        doc.add_paragraph("") # Spacing
        
        # Salutation
        doc.add_paragraph("Dear Sir/Madam,")
        
        # Subject
        subject = doc.add_paragraph(f"SUBJECT: NOTICE REGARDING LEGAL RIGHTS")
        subject.runs[0].bold = True
        
        # Body (Generated by AI)
        body_text = letter_data.get('formal_body', 'Content missing.')
        doc.add_paragraph(body_text)
        
        # Closing
        doc.add_paragraph("")
        doc.add_paragraph("Yours faithfully,")
        doc.add_paragraph("")
        doc.add_paragraph("__________________________")
        doc.add_paragraph(user_name)
        
        # Save to memory buffer
        buffer = io.BytesIO()
        doc.save(buffer)
        buffer.seek(0)
        return buffer